mediacontrol/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()

import os
PROJECT_DIR = os.path.dirname(__file__)

urlpatterns = patterns('',
                       (r'^files/(?P<path>.*)$', 'django.views.static.serve', {'document_root': PROJECT_DIR + '/files'}),
                       (r'^$', 'mediacontrol.core.views.index'),
                       (r'^add/solicitud/$', 'mediacontrol.core.views.add_solicitud'),
                       (r'^add/persona/$', 'mediacontrol.core.views.add_persona'),
                       (r'^edit/persona/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.edit_persona'),
                       (r'^add/material/$', 'mediacontrol.core.views.add_material'),
                       (r'^edit/material/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.edit_material'),
                       (r'^add/otros/$', 'mediacontrol.core.views.add_otros'),
                       (r'^add/otros/tipo/$', 'mediacontrol.core.views.add_otros_tipo'),
                       (r'^add/otros/tipo/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.add_otros_tipo_edit'),
                       (r'^add/otros/tematica/$', 'mediacontrol.core.views.add_otros_tematica'),
                       (r'^add/otros/tematica/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.add_otros_tematica_edit'),
                       (r'^add/otros/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.add_otros_edit'),
                       (r'^load/$', 'mediacontrol.core.views.load'),
                       (r'^load/registrar/$', 'mediacontrol.core.views.registrar'),
                       (r'^reporte/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.reportar'),
                       (r'^reportes/$', 'mediacontrol.core.views.reportes'),
                       (r'^reportes/materiales/$', 'mediacontrol.core.views.material_report'),
                       (r'^graficos/$', 'mediacontrol.core.views.graficos'),

                       #vistas para busqueda
                       (r'^buscar/solicitud/$', 'mediacontrol.core.views.buscar_solicitud'),

                       #URLs para las vistas relacionadas con ajax
                       (r'^ajax/profesion/$', 'mediacontrol.core.views.get_profesiones'),
                       (r'^ajax/personas/$', 'mediacontrol.core.views.get_materiales'),
                       (r'^ajax/org2/$', 'mediacontrol.core.views.get_orgs'),
                       (r'^ajax/tematica/$', 'mediacontrol.core.views.get_tematicas'),
                       (r'^ajax/tipos/$', 'mediacontrol.core.views.get_tipos'),
                       (r'^ajax/borrar-profesion/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.del_profesiones'),
                       (r'^ajax/borrar-tipo/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.del_tipo'),
                       (r'^ajax/borrar-tematica/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.del_tematica'),
                       (r'^ajax/borrar-material/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.del_material'),
                       (r'^ajax/borrar-solicitante/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.del_persona'),

                       (r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
                       (r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'logout.html'}),
                       (r'^admin/', include(admin.site.urls)),
                       )

mediacontrol/core/models.py
# -*- coding: UTF-8 -*-

from django.db import models

class Profesion(models.Model):
    nombre = models.CharField(max_length=100)
    
    def __unicode__(self):
        return self.nombre
    
    class Meta:
        verbose_name = 'Profesion'
        verbose_name_plural = 'Profesiones'

class Organizacion(models.Model):
    nombre = models.CharField(max_length=100)

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = 'Organizaciones'

SEXOS = (('femenino', 'Femenino'), ('masculino', 'Masculino'))

class Persona(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    sexo = models.CharField(max_length=10, choices=SEXOS)
    email = models.EmailField(blank=True, null=True)
    telefono = models.CharField(max_length=30, null=True, blank=True)
    #organizacion = models.CharField(max_length=200)
    org2 = models.ForeignKey(Organizacion)
    profesion = models.ManyToManyField(Profesion)

    def __unicode__(self):
        return '%s %s' % (self.nombre, self.apellido)

    class Meta:
        verbose_name = 'Persona'
        verbose_name_plural = 'Personas'

class Tipo(models.Model):
    nombre = models.CharField(max_length=100)

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Tipo'
        verbose_name_plural = 'Tipos'

class Tematica(models.Model):
    nombre = models.CharField(max_length=150)

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Tematica'
        verbose_name_plural = 'Tematicas'

class Material(models.Model):
    codigo = models.CharField(max_length=100, unique=True)
    titulo = models.CharField(max_length=200)
    #autor = models.CharField(max_length=100, null=True, blank=True)
    tematica = models.ManyToManyField(Tematica)
    tipo = models.ForeignKey(Tipo)
    #cantidad = models.IntegerField()

    def __unicode__(self):
        return self.codigo + '-' + self.titulo

    class Meta:
        verbose_name = 'Material'
        verbose_name_plural = 'Materiales'

class Solicitud(models.Model):
    persona = models.ForeignKey(Persona)    
    fecha = models.DateTimeField()

    def __unicode__(self):
        return self.persona.nombre

    class Meta:
        verbose_name = 'Solicitud'
        verbose_name_plural = 'Solicitudes'    

class Agregado(models.Model):
    solicitud = models.ForeignKey(Solicitud)
    material = models.ForeignKey(Material)
    cantidad = models.IntegerField()

    def __unicode__(self):
        return 'Solicitud %s' % (self.solicitud.pk)
    
    class Meta:
        verbose_name_plural = 'Agregados'

mediacontrol/templates/reportes/materiales.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Solicitud {{s.fecha}}</title>
        <style type="text/css">
            @page {
                size: A4 portrait;
                margin: 1cm;
                @frame footer {
                -pdf-frame-content: footerContent;
                bottom: 0cm;
                margin-left: 9cm;
                margin-right: 9cm;
                height: 1cm;
            }
            }
            body{
                font-size: 12px;
                font-family: 'Trebuchet MS', sans-serif;
            }
            th{
                background-color: #ded3ba;
                font-family: 'Trebuchet MS', sans-serif;
            }
            td, th{
                border: 1px solid #E0DDD2;
                padding: 3px 2px -1px 8px;
            }
            .datos span{
                font-weight: bold;
                line-height: 16px;
            }
            .materiales{
                font-size: 10px;
            }
        </style>
    </head>
    <body>
        <div>
            <img src="http://mcontrol.fundacionluciernaga.org/files/images/logo.jpg" alt="">
            <div class="datos"><br><br>
                <span style="font-size: 14px;">Materiales registrados {{mes}} {{anio}}</span><br><br>
            </div>
            <br><br>
            <table class="mostrar">
                <thead>
                    <tr>
                        <th>C&oacute;digo</th>
                        <th>T&iacute;tulo</th>                        
                        <th>Tipo</th>
                        <th>Tem&aacute;tica</th>                        
                    </tr>
                </thead>
                <tbody>
                    {% for material in materiales %}
                    <tr>
                        <td>{{material.codigo}}</td>
                        <td>{{material.titulo}}</td>                        
                        <td>{{material.tipo}}</td>
                        <td class="materiales">
                            {% for i in material.tematica.all %}
                            {{i.nombre}}{% if forloop.last %}{% else %}, {% endif %}
                            {% endfor %}
                        </td>                        
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div id="footerContent">
            {%block page_foot%}
            P&aacute;gina <pdf:pagenumber>
                {%endblock%}
        </div>
    </body>
</html>

mediacontrol/templates/reportes/solicitud.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <title>Solicitud {{s.fecha}}</title>
        <style type="text/css">
            @page {
                size: A4 portrait;
                margin: 1cm;
                @frame footer {
                -pdf-frame-content: footerContent;
                bottom: 0cm;
                margin-left: 9cm;
                margin-right: 9cm;
                height: 1cm;
            }
            }
            body{
                font-size: 12px;
                font-family: 'Trebuchet MS', sans-serif;
            }
            td, th{
                border-right: 1px solid #E0DDD2;
                border-bottom: 1px solid #E0DDD2;                
            }
            td{
                padding: 6px 12px 6px 12px;
            }
        </style>
    </head>
    <body>
        <div>
            <img src="http://mcontrol.fundacionluciernaga.org/files/images/logo.jpg" alt=""><br>
            Nombre del solicitante: {{s.persona}}<br>
            Organismo al que pertenece: {{s.persona.organizacion}}<br>
            Correo Electr&oacute;nico: {{s.persona.email}} Tel&eacute;fono: {{s.persona.telefono}}<br>
            Fecha: {{s.fecha}}<br>
            Profesi&oacute;n:<br>
            {% for a in s.persona.profesion.all %}
            {{a.nombre}}{% if forloop.last %} {% else %}, {% endif %}
            {% endfor %}
            <table class="mostrar">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Titulos</th>
                        <th>Cantidad</th>
                    </tr>
                </thead>
                <tbody>
                    {% for m in s.material.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{m.titulo}}</td>
                        <td>{{m.cantidad}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div id="footerContent">
            {%block page_foot%}
            P&aacute;gina <pdf:pagenumber>
                {%endblock%}
        </div>

    </body>
</html>

mediacontrol/templates/reportes/solicitudes.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Solicitud {{s.fecha}}</title>
        <style type="text/css">
            @page {
                size: A4 portrait;
                margin: 1cm;
                @frame footer {
                -pdf-frame-content: footerContent;
                bottom: 0cm;
                margin-left: 9cm;
                margin-right: 9cm;
                height: 1cm;
            }
            }
            body{
                font-size: 12px;
                font-family: 'Trebuchet MS', sans-serif;
            }
            th{
                background-color: #ded3ba;
                font-family: 'Trebuchet MS', sans-serif;                
            }
            td, th{
                border: 1px solid #E0DDD2;
                padding: 3px 2px -1px 8px;
            }
            .datos span{
                font-weight: bold;
                line-height: 16px;
            }
            .materiales{
                font-size: 10px;
            }            
        </style>
    </head>
    <body>
        <div>
            <img src="http://mcontrol.fundacionluciernaga.org/files/images/logo.jpg" alt="">
            <div class="datos"><br><br>
                <span style="font-size: 14px;">Filtros</span><br><br>
                <span>Meses: </span>{% for m in meses %}{{m}}{% if forloop.last %}{% else %}, {% endif %}{% endfor %}<br>
                <span>A&ntilde;o: </span>{{anio}}
            </div>
            <br><br>
            <table class="mostrar">
                <thead>
                    <tr>
                        <th>Id.</th>
                        <th>Fecha</th>
                        <th>Solicitante</th>
                        <th>Materiales</th>
                    </tr>
                </thead>
                <tbody>
                    {% for solicitud in s %}
                    <tr>
                        <td>{{solicitud.id}}</td>
                        <td>{{solicitud.fecha}}</td>
                        <td>{{solicitud.persona}}</td>
                        <td class="materiales">
                            {% for i in solicitud.agregado_set.all %}
                            {{i.material.titulo}}{% if forloop.last %}{% else %}, {% endif %}
                            {% endfor %}
                        </td>
                    </tr>
                    {% endfor %}                    
                </tbody>
            </table>
        </div>
        <div id="footerContent">            
            {%block page_foot%}
            P&aacute;gina <pdf:pagenumber>
                {%endblock%}
        </div>
    </body>
</html>