mediacontrol/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()

import os
PROJECT_DIR = os.path.dirname(__file__)

urlpatterns = patterns('',
                       (r'^files/(?P<path>.*)$', 'django.views.static.serve', {'document_root': PROJECT_DIR + '/files'}),
                       (r'^$', 'mediacontrol.core.views.index'),
                       (r'^add/solicitud/$', 'mediacontrol.core.views.add_solicitud'),
                       (r'^add/persona/$', 'mediacontrol.core.views.add_persona'),
                       (r'^edit/persona/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.edit_persona'),
                       (r'^add/material/$', 'mediacontrol.core.views.add_material'),
                       (r'^edit/material/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.edit_material'),
                       (r'^add/otros/$', 'mediacontrol.core.views.add_otros'),
                       (r'^add/otros/tipo/$', 'mediacontrol.core.views.add_otros_tipo'),
                       (r'^add/otros/tipo/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.add_otros_tipo_edit'),
                       (r'^add/otros/tematica/$', 'mediacontrol.core.views.add_otros_tematica'),
                       (r'^add/otros/tematica/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.add_otros_tematica_edit'),
                       (r'^add/otros/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.add_otros_edit'),
                       (r'^load/$', 'mediacontrol.core.views.load'),
                       (r'^load/registrar/$', 'mediacontrol.core.views.registrar'),
                       (r'^reporte/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.reportar'),
                       (r'^reportes/$', 'mediacontrol.core.views.reportes'),
                       (r'^reportes/materiales/$', 'mediacontrol.core.views.material_report'),
                       (r'^graficos/$', 'mediacontrol.core.views.graficos'),

                       #vistas para busqueda
                       (r'^buscar/solicitud/$', 'mediacontrol.core.views.buscar_solicitud'),

                       #URLs para las vistas relacionadas con ajax
                       (r'^ajax/profesion/$', 'mediacontrol.core.views.get_profesiones'),
                       (r'^ajax/personas/$', 'mediacontrol.core.views.get_materiales'),
                       (r'^ajax/org2/$', 'mediacontrol.core.views.get_orgs'),
                       (r'^ajax/tematica/$', 'mediacontrol.core.views.get_tematicas'),
                       (r'^ajax/tipos/$', 'mediacontrol.core.views.get_tipos'),
                       (r'^ajax/borrar-profesion/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.del_profesiones'),
                       (r'^ajax/borrar-tipo/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.del_tipo'),
                       (r'^ajax/borrar-tematica/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.del_tematica'),
                       (r'^ajax/borrar-material/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.del_material'),
                       (r'^ajax/borrar-solicitante/(?P<id>[-\w]+)/$', 'mediacontrol.core.views.del_persona'),

                       (r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
                       (r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'logout.html'}),
                       (r'^admin/', include(admin.site.urls)),
                       )

mediacontrol/core/models.py
# -*- coding: UTF-8 -*-

from django.db import models

class Profesion(models.Model):
    nombre = models.CharField(max_length=100)
    
    def __unicode__(self):
        return self.nombre
    
    class Meta:
        verbose_name = 'Profesion'
        verbose_name_plural = 'Profesiones'

class Organizacion(models.Model):
    nombre = models.CharField(max_length=100)

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = 'Organizaciones'

SEXOS = (('femenino', 'Femenino'), ('masculino', 'Masculino'))

class Persona(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    sexo = models.CharField(max_length=10, choices=SEXOS)
    email = models.EmailField(blank=True, null=True)
    telefono = models.CharField(max_length=30, null=True, blank=True)
    #organizacion = models.CharField(max_length=200)
    org2 = models.ForeignKey(Organizacion)
    profesion = models.ManyToManyField(Profesion)

    def __unicode__(self):
        return '%s %s' % (self.nombre, self.apellido)

    class Meta:
        verbose_name = 'Persona'
        verbose_name_plural = 'Personas'

class Tipo(models.Model):
    nombre = models.CharField(max_length=100)

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Tipo'
        verbose_name_plural = 'Tipos'

class Tematica(models.Model):
    nombre = models.CharField(max_length=150)

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Tematica'
        verbose_name_plural = 'Tematicas'

class Material(models.Model):
    codigo = models.CharField(max_length=100, unique=True)
    titulo = models.CharField(max_length=200)
    #autor = models.CharField(max_length=100, null=True, blank=True)
    tematica = models.ManyToManyField(Tematica)
    tipo = models.ForeignKey(Tipo)
    #cantidad = models.IntegerField()

    def __unicode__(self):
        return self.codigo + '-' + self.titulo

    class Meta:
        verbose_name = 'Material'
        verbose_name_plural = 'Materiales'

class Solicitud(models.Model):
    persona = models.ForeignKey(Persona)    
    fecha = models.DateTimeField()

    def __unicode__(self):
        return self.persona.nombre

    class Meta:
        verbose_name = 'Solicitud'
        verbose_name_plural = 'Solicitudes'    

class Agregado(models.Model):
    solicitud = models.ForeignKey(Solicitud)
    material = models.ForeignKey(Material)
    cantidad = models.IntegerField()

    def __unicode__(self):
        return 'Solicitud %s' % (self.solicitud.pk)
    
    class Meta:
        verbose_name_plural = 'Agregados'

mediacontrol/core/forms.py
# -*- coding: UTF-8 -*-

from django import forms as forms
from models import *


class SolicitudForm(forms.ModelForm):
    persona = forms.CharField(max_length=200, label='Solicitante')
    material = forms.CharField(max_length=200)
    userid = forms.CharField(max_length=50, widget=forms.HiddenInput())
    #fecha = forms.DateTimeField(initial=datetime.datetime.now())
    class Meta:
        model = Solicitud
        fields = ['persona', 'material', 'fecha']   

class MaterialForm(forms.ModelForm):
    tematica = forms.ModelMultipleChoiceField(queryset=Tematica.objects.all(), widget=forms.CheckboxSelectMultiple, help_text="")
    class Meta:
        model = Material
        #widgets = {'tematica': forms.CheckboxSelectMultiple}

class PersonaForm(forms.ModelForm):
    org = forms.CharField(max_length=150, label='Organizacion')
    profesion = forms.ModelMultipleChoiceField(queryset=Profesion.objects.all(), widget=forms.CheckboxSelectMultiple, help_text="")
    class Meta:
        model = Persona
        exclude = ['org2']
        fields = ['nombre', 'apellido', 'sexo', 'email', 'telefono', 'org', 'profesion']
        
class ProfesionForm(forms.ModelForm):
    class Meta:
        model = Profesion

class TipoForm(forms.ModelForm):
    class Meta:
        model = Tipo

class TematicaForm(forms.ModelForm):
    class Meta:
        model = Tematica

def get_months():
    s = Solicitud.objects.all().order_by('fecha')
    dicc = {
        1:'Enero',
        2:'Febrero',
        3:'Marzo',
        4:'Abril',
        5:'Mayo',
        6:'Junio',
        7:'Julio',
        8:'Agosto',
        9:'Septiembre',
        10:'Octubre',
        11:'Noviembre',
        12:'Diciembre'
    }
    choices = []
    meses = []
    for i in s:
        meses.append(int(i.fecha.month))    
    for a in sorted(list(set(meses))):
        lista = []
        lista.append(a)
        lista.append(dicc[int(a)])
        choices.append(lista)
    return choices

def get_years():
    s = Solicitud.objects.all()
    years = []
    data = []
    for a in s:
        years.append(a.fecha.year)
    for y in sorted(list(set(years))):
        lista = []
        lista.append(y)
        lista.append(str(y))
        data.append(lista)
    return data

class ReportForm(forms.Form):
    mes = forms.MultipleChoiceField(choices=get_months())
    anio = forms.ChoiceField(choices=get_years(), label='Año')    


VARS = (('sexo','Sexo'), ('organizacion', 'Organizacion'))
class VariablesForm(forms.Form):
    variable = forms.ChoiceField(choices=VARS, label='Seleccione la variable')
    anio = forms.ChoiceField(choices=get_years(), label='Año')

mediacontrol/templates/add_solicitud.html
{% extends "base.html" %}
{% block leftmenu %}
{% include "left_add.html" %}
{% endblock %}

mediacontrol/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <title> Control de Materiales Audiovisuales {% block extratitle %}{% endblock %}</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link type="image/x-icon" rel="shortcut icon" href="/files/images/favicon.ico">
        <link type="text/css" rel="stylesheet"  href="/files/css/site.css" >
        <link type="text/css" rel="stylesheet" href="/files/css/style.css">
        <link type="text/css" rel="stylesheet" href="/files/css/jquery.autocomplete.css">
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
        <script type="text/javascript" src="/files/js/jquery.cookie.js"></script>
        <script type="text/javascript" src="/files/js/jquery.autocomplete.min.js"></script>
        <script type='text/javascript' src='/files/js/menu.js'></script>        
        {% block extrahead %}
        {% endblock %}
    </head>
    <body>
        <div class="content">
            <div class="menu_top">
                <ul id="nav">
                    <li class="l1"><a class="uno" href="/">Home</a>
                    <li class="l1"><a class="uno" href="#">Buscar</a>
                    <li class="l1"><a class="uno" href="#">Agregar</a>
                        <ul>
                            <li><a href="/add/solicitud/">Solicitud</a>
                                <!--<ul>
                                    <li><a href="#">3.1.1 Download</a></li>
                                    <li><a href="#">3.1.2 Tutorial</a></li>
                                </ul>-->
                            </li>
                            <li><a href="/add/persona/">Persona</a></li>
                            <li><a href="/add/material/">Material</a></li>
                            <li><a href="/add/otros/">Otros</a></li>
                        </ul>

                    </li>
                    <li class="l1"><a class="uno" href="/reportes/">Reportes</a>
                        <ul>
                            <li><a href="/reportes/">Generar</a>
                            <li><a href="/graficos/">Gr&aacute;ficos</a>
                        </ul>
                    </li>                    
                    <li class="l1"><a href="/logout/">Salir</a></li>
                </ul>
            </div>           
            <div class="logo">
                <a href="/"><img alt="Logo" src="/files/images/logo.png"></a>
            </div>
            <div class="nombre">
                <img class="line" alt="line" src="/files/images/line_2.png">
            </div>
            <div class="main">
                <div class="left">
                    {% block leftmenu %}{% endblock %}
                </div>
                <div class="center">
                    <div class="top"></div>
                    <div class="mid">
                        {% block data %}{% endblock %}
                        <br style="clear: both;">
                    </div>
                    <div  class="footer"></div>
                </div>
            </div>
        </div>
    </body>    
</html>

mediacontrol/templates/buscar.html
{% extends "base.html" %}

{% block extrahead %}
<style type="text/css">
    .selected{
        background: url(/files/images/row2.png) no-repeat right;
    }
</style>
{% endblock %}

{% block leftmenu %}
{% include "left_buscar.html" %}
{% endblock %}

{% block data %}

{% endblock %}

mediacontrol/templates/index.html
{% extends "base.html" %}
{% block leftmenu %}
{% include "left_add.html" %}
{% endblock %}

{% block data %}
<img style="margin-bottom: -8px;" src="/files/images/index.png" alt="Fundacion">
{% endblock %}

mediacontrol/templates/left_add.html
<ul>
    <li class="title">Agregar</li>
    <li><a {% ifequal flag 'solicitud' %}class="selected" style="color: #6c6c6c;"{% endifequal %} href="/add/solicitud/">Solicitud</a></li>
    <li><a {% ifequal flag 'persona' %}class="selected" style="color: #6c6c6c;"{% endifequal %} href="/add/persona/">Persona</a></li>
    <li><a {% ifequal flag 'material' %}class="selected" style="color: #6c6c6c;"{% endifequal %} href="/add/material/">Material</a>
    <li><a {% ifequal flag 'otros' %}class="selected" style="color: #6c6c6c;"{% endifequal %} href="/add/otros/">Otros</a>
    <li class="footer"></li>
</ul>

mediacontrol/templates/left_buscar.html
<ul>
    <li class="title">Buscar</li>
    <li><a {% ifequal flag 'solicitud' %}class="selected" style="color: #6c6c6c;"{% endifequal %} href="/buscar/solicitud/">Solicitud</a></li>
    <li><a {% ifequal flag 'persona' %}class="selected" style="color: #6c6c6c;"{% endifequal %} href="/buscar/persona/">Persona</a></li>
    <li><a {% ifequal flag 'material' %}class="selected" style="color: #6c6c6c;"{% endifequal %} href="/buscar/material/">Material</a></li>
    <li class="footer"></li>
</ul>

mediacontrol/templates/left_reportes.html
<ul>
    <li class="title">Reportes</li>
    <li><a {% ifequal flag 'reportes' %}class="selected" style="color: #6c6c6c;"{% endifequal %} href="/reportes/">Generar</a></li>
    <li><a {% ifequal flag 'graficos' %}class="selected" style="color: #6c6c6c;"{% endifequal %} href="/graficos/">Gr&aacute;ficos</a></li>
    <li class="footer"></li>
</ul>

mediacontrol/templates/login.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Iniciar Sesi&oacute;n | Luci&eacute;rnaga</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
        <link rel='stylesheet' type='text/css' href='/files/css/login.css'>
        <style type="text/css">
            body{
                background: #eee;
            }            
            .top{
                /*background-color: #79993c;*/
                background: url(/files/images/login-back.png) repeat-x;
                width: 350px;
                height: 40px;
                line-height: 40px;
                text-align: center;
                font-size: 20px;
                color: #fff;
            }
            .edit-form{
                width: 350px;
                height: 200px;
            }
        </style>
    </head>
    <body>
        <div class="login">            
            <div class="edit-form">
                <div class="top">
                    Iniciar Sesión | Luci&eacute;rnaga
                </div>
                <form action="{% url django.contrib.auth.views.login %}" method="POST">{% csrf_token %}
                    <table>
                        <tr><td colspan="2" id="gral"></td></tr>
                        <tr><th><label for="id_username">Usuario:</label></th><td><input id="id_username" type="text" name="username" maxlength="30" /></td></tr>
                        <tr><th><label for="id_password">Contraseña:</label></th><td><input type="password" name="password" id="id_password" /></td></tr>
                    </table>
                    <button type="submit" class="submit">Entrar</button>
                    <input type="hidden" name="next" value="{{ next }}" />
                </form>
            </div>
            <script type="text/javascript">
                document.getElementById('id_username').focus()
            </script>
        </div>
    </body>
</html>

mediacontrol/templates/otros.html
{% extends "base.html" %}

{% block extrahead %}
<style type="text/css">
    .selected{
        background: url(/files/images/row2.png) no-repeat right;
    }	
</style>
<script type="text/javascript" src="/files/js/site.js"></script>
{% endblock %}

{% block leftmenu %}
{% include "left_add.html" %}
{% endblock %}

{% block data %}
<div style="margin-left: 15px; padding-top: 15px; width: 350px; float: left;">
    <img class="aux" src="/files/images/profesion.png" alt="Agregar profesion">
    <span class="title">Agregar Profesi&oacute;n</span>
    <a id="view_pro" href="#" style="font-size:11px; color: #069;">(Ver existentes)</a>
    <form action="/add/otros/" method="POST">{% csrf_token %}
        <label for="id_nombre">{{form.nombre.label}}: </label>{{form.nombre}}        
        <input type="submit" value="Guardar" /><br>
		{{form.nombre.errors}}		
    </form>
    <br><br>
    <img class="aux" src="/files/images/tipo_material.png" alt="Tipo material">
    <span class="title">Agregar Tipo de Material</span>
    <a id="view_tipos" href="#" style="font-size:11px; color: #069;">(Ver existentes)</a>
    <form action="/add/otros/tipo/" method="POST">{% csrf_token %}
        <label for="id_nombre">{{form_tipo.nombre.label}}: </label>{{form_tipo.nombre}}        
        <input type="submit" value="Guardar" /><br>
		{{form_tipo.nombre.errors}}
    </form>
    <br><br>
    <img class="aux" src="/files/images/tematica.png" alt="Tematica">
    <span class="title">Agregar Tem&aacute;tica</span>
    <a id="view_temas" href="#" style="font-size:11px; color: #069;">(Ver existentes)</a>
    <form action="/add/otros/tematica/" method="POST">{% csrf_token %}
        <label for="id_nombre">{{form_tematica.nombre.label}}: </label>{{form_tematica.nombre}}        
        <input type="submit" value="Guardar" /><br>
		{{form_tematica.nombre.errors}}
    </form>
</div>
<div id="resultado" style="padding-top: 15px; width: 290px; float: left;">
</div>
<br><br>
{% endblock %}

mediacontrol/templates/otros_edit_profesion.html
{% extends "base.html" %}
{% block extrahead %}
<style type="text/css">
    .selected{
        background: url(/files/images/row2.png) no-repeat right;
    }	
</style>
<script type="text/javascript" src="/files/js/site.js"></script>
{% endblock %}

{% block leftmenu %}
{% include "left_add.html" %}
{% endblock %}

{% block data %}
<div>
    <div style="margin-left: 15px; padding-top: 15px; width: 350px;">
        <img class="aux" src="/files/images/profesion.png" alt="Agregar profesion">
        <span class="title">Editar Profesi&oacute;n</span>
        <a id="view_pro" href="#" style="font-size:11px; color: #069;">(Ver existentes)</a>
        <form action="." method="POST">{% csrf_token %}
            <label for="id_nombre">{{form.nombre.label}}: </label>{{form.nombre}}
            <input type="submit" value="Guardar" /><br>
		{{form.nombre.errors}}		
        </form>
        <br><br>
        <img class="aux" src="/files/images/tipo_material.png" alt="Tipo material">
        <span class="title">Agregar Tipo de Material</span>
        <a id="view_tipos" href="#" style="font-size:11px; color: #069;">(Ver existentes)</a>
        <form action="/add/otros/tipo/" method="POST">{% csrf_token %}
            <label for="id_nombre">{{form_tipo.nombre.label}}: </label>{{form_tipo.nombre}}
            <input type="submit" value="Guardar" /><br>
		{{form_tipo.nombre.errors}}
        </form>
        <br><br>
        <img class="aux" src="/files/images/tematica.png" alt="Tematica">
        <span class="title">Agregar Tem&aacute;tica</span>
        <a id="view_temas" href="#" style="font-size:11px; color: #069;">(Ver existentes)</a>
        <form action="/add/otros/tematica/" method="POST">{% csrf_token %}
            <label for="id_nombre">{{form_tematica.nombre.label}}: </label>{{form_tematica.nombre}}
            <input type="submit" value="Guardar" /><br>
		{{form_tematica.nombre.errors}}
        </form>
    </div>
    <div id="resultado" style="padding-top: 15px; position: absolute; width: 290px; left: 590px; top: 200px;">
    </div>
    <br><br>
</div>
{% endblock %}

mediacontrol/templates/otros_edit_tematica.html
{% extends "base.html" %}
{% block extrahead %}
<style type="text/css">
    .selected{
        background: url(/files/images/row2.png) no-repeat right;
    }
</style>
<script type="text/javascript" src="/files/js/site.js"></script>
{% endblock %}

{% block leftmenu %}
{% include "left_add.html" %}
{% endblock %}

{% block data %}
<div>
    <div style="margin-left: 15px; padding-top: 15px; width: 350px;">
        <img class="aux" src="/files/images/profesion.png" alt="Agregar profesion">
        <span class="title">Agregar Profesi&oacute;n</span>
        <a id="view_pro" href="#" style="font-size:11px; color: #069;">(Ver existentes)</a>
        <form action="/add/otros/" method="POST">{% csrf_token %}
            <label for="id_nombre">{{form.nombre.label}}: </label>{{form.nombre}}
            <input type="submit" value="Guardar" /><br>
		{{form.nombre.errors}}
        </form>
        <br><br>
        <img class="aux" src="/files/images/tipo_material.png" alt="Tipo material">
        <span class="title">Agregar Tipo de Material</span>
        <a id="view_tipos" href="#" style="font-size:11px; color: #069;">(Ver existentes)</a>
        <form action="/add/otros/tipo/" method="POST">{% csrf_token %}
            <label for="id_nombre">{{form_tipo.nombre.label}}: </label>{{form_tipo.nombre}}
            <input type="submit" value="Guardar" /><br>
		{{form_tipo.nombre.errors}}
        </form>
        <br><br>
        <img class="aux" src="/files/images/tematica.png" alt="Tematica">
        <span class="title">Editar Tem&aacute;tica</span>
        <a id="view_temas" href="#" style="font-size:11px; color: #069;">(Ver existentes)</a>
        <form action="." method="POST">{% csrf_token %}
            <label for="id_nombre">{{form_tematica.nombre.label}}: </label>{{form_tematica.nombre}}
            <input type="submit" value="Guardar" /><br>
		{{form_tematica.nombre.errors}}
        </form>
    </div>
    <div id="resultado" style="padding-top: 15px; position: absolute; width: 290px; left: 590px; top: 200px;">
    </div>
    <br><br>
</div>
{% endblock %}

mediacontrol/templates/otros_edit_tipo.html
{% extends "base.html" %}
{% block extrahead %}
<style type="text/css">
    .selected{
        background: url(/files/images/row2.png) no-repeat right;
    }
</style>
<script type="text/javascript" src="/files/js/site.js"></script>
{% endblock %}

{% block leftmenu %}
{% include "left_add.html" %}
{% endblock %}

{% block data %}
<div>
    <div style="margin-left: 15px; padding-top: 15px; width: 350px;">
        <img class="aux" src="/files/images/profesion.png" alt="Agregar profesion">
        <span class="title">Agregar Profesi&oacute;n</span>
        <a id="view_pro" href="#" style="font-size:11px; color: #069;">(Ver existentes)</a>
        <form action="/add/otros/" method="POST">{% csrf_token %}
            <label for="id_nombre">{{form.nombre.label}}: </label>{{form.nombre}}
            <input type="submit" value="Guardar" /><br>
		{{form.nombre.errors}}
        </form>
        <br><br>
        <img class="aux" src="/files/images/tipo_material.png" alt="Tipo material">
        <span class="title">Editar Tipo de Material</span>
        <a id="view_tipos" href="#" style="font-size:11px; color: #069;">(Ver existentes)</a>
        <form action="." method="POST">{% csrf_token %}
            <label for="id_nombre">{{form_tipo.nombre.label}}: </label>{{form_tipo.nombre}}
            <input type="submit" value="Guardar" /><br>
		{{form_tipo.nombre.errors}}
        </form>
        <br><br>
        <img class="aux" src="/files/images/tematica.png" alt="Tematica">
        <span class="title">Agregar Tem&aacute;tica</span>
        <a id="view_temas" href="#" style="font-size:11px; color: #069;">(Ver existentes)</a>
        <form action="/add/otros/tematica/" method="POST">{% csrf_token %}
            <label for="id_nombre">{{form_tematica.nombre.label}}: </label>{{form_tematica.nombre}}
            <input type="submit" value="Guardar" /><br>
		{{form_tematica.nombre.errors}}
        </form>
    </div>
    <div id="resultado" style="padding-top: 15px; position: absolute; width: 290px; left: 590px; top: 200px;">
    </div>
    <br><br>
</div>
{% endblock %}

mediacontrol/templates/registrar.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
        <script type="text/javascript" src="/files/js/jquery.autocomplete.min.js"></script>
        <link type="text/css" rel="stylesheet"  href="/files/css/site.css" >
        <link type="text/css" rel="stylesheet" href="/files/css/jquery.autocomplete.css">
        <style type="text/css">
            body{
                background: none;
            }
        </style>
        <script>
            /*$(document).ready(function(){
                $('.agregar').click(function(){
                    var id = $(this).attr('id');
                    var nombre = $('#'+id+'_nombre').html();
                    $('#id_persona', window.parent.document).val(nombre);
                    $('#id_userid', window.parent.document).val(id);
                    window.parent.$.modal.close(true);
                    return false;
                });
            });*/
            $(document).ready(function(){
                $('#id_org').autocomplete('/ajax/org2/');
                $('#registrar').submit(function(){
                    var datos = $('#registrar').serialize();
                    $.post('/load/registrar/', datos,
                    function(data){
                        $('#id_persona', window.parent.document).val(data[1]);
                        $('#id_userid', window.parent.document).val(data[0]);
                        window.parent.$.modal.close(true);                        
                    }, "json");
                    return false;
                });
            });
        </script>
    </head>
    <body>
        <img style="float: right; margin-right: 40px;" src="/files/images/persona.png" alt="Solicitantes">
        <div style="margin-left: 80px; margin-top: 30px;">
            <span style="color: #069;">Agregar solicitante</span><br><br>
            <form style="margin:0;" action="." method="POST" id="registrar">{% csrf_token %}
                <table>
                    {{form.as_table}}
                    <tr><td><input type="submit" value="Guardar" /></td></tr>
                </table>
            </form>
        </div>
    </body>
</html>